environment:
  PROJECT_LEVEL: PROJECT_LEVEL
packages:
  - name: nondefault
    environment:
      PACKAGE_LEVEL: PACKAGE_LEVEL
    actions:
      - name: vars
        runtime: go:default
        environment:
          ACTION_LEVEL: ACTION_LEVEL
  - name: load
    environment:
      DATABASE_URL: "${DATABASE_URL}"