environment:
  PROJECT_LEVEL: PROJECT_LEVEL
packages:
  - name: default
    environment:
      PACKAGE_LEVEL: PACKAGE_LEVEL
    actions:
      - name: concurrency
        environment:
          ACTION_LEVEL: ACTION_LEVEL